/**
 * Emit a generated `pipeline.ts` / `release.ts` / `shared.ts` from a list of
 * categorized predefined variables. Each output is a nested `as const` object
 * literal grouped by the first dotted segment (e.g. `Build`, `System`).
 *
 * TSDoc on each leaf is the description verbatim from MS Learn. Any
 * comment-block-closing sequences in source descriptions are escaped
 * (zero-width space inserted between the asterisk and slash) by
 * `sanitizeComment` so they cannot terminate the doc block early.
 */

import { groupByCategory, type CategorizedVariable } from './categorize.js';

const AZURE_DOCS_PIPELINE = 'https://learn.microsoft.com/azure/devops/pipelines/build/variables';
const AZURE_DOCS_RELEASE = 'https://learn.microsoft.com/azure/devops/pipelines/release/variables';

/** Make text safe to embed inside a doc-comment block. */
function sanitizeComment(text: string): string {
  return text
    // eslint-disable-next-line no-control-regex -- intentionally strip NUL bytes from upstream content
    .replace(/\u0000/g, '')
    .replace(/\r\n?/g, '\n')
    .replace(/\t/g, '  ')
    .replace(/\*\//g, '*\u200B/');
}

function wrapParagraph(text: string, width = 92): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [];
  const lines: string[] = [];
  let line = '';
  for (const w of words) {
    if (line.length === 0) line = w;
    else if (line.length + 1 + w.length <= width) line += ' ' + w;
    else {
      lines.push(line);
      line = w;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function renderTsdoc(paragraphs: (string | undefined)[], indent = ''): string {
  const cleaned = paragraphs
    .filter((p): p is string => typeof p === 'string' && p.trim().length > 0)
    .map((p) => sanitizeComment(p.trim()));
  if (cleaned.length === 0) return '';
  const lines: string[] = [`${indent}/**`];
  cleaned.forEach((para, i) => {
    if (i > 0) lines.push(`${indent} *`);
    for (const sub of para.split('\n')) {
      const wrapped = wrapParagraph(sub.trim());
      if (wrapped.length === 0) lines.push(`${indent} *`);
      else for (const w of wrapped) lines.push(`${indent} * ${w}`);
    }
  });
  lines.push(`${indent} */`);
  return lines.join('\n') + '\n';
}

export interface EmitOptions {
  /** Top-level export name (`Pipeline` / `Release` / `Shared`). */
  exportName: string;
  /** Header docs for the file. */
  headerDoc: string;
  /** Which docs URL to embed in `@azureDocs` tags. */
  docsUrl: 'pipeline' | 'release' | 'both';
}

/**
 * Render the body of a generated TS file. Sorts groups + entries
 * deterministically so re-running on unchanged input yields zero diff.
 */
export function emitVarsFile(
  vars: CategorizedVariable[],
  opts: EmitOptions,
): string {
  const docsTags: string[] =
    opts.docsUrl === 'pipeline'
      ? [`@azureDocs ${AZURE_DOCS_PIPELINE}`]
      : opts.docsUrl === 'release'
        ? [`@azureDocs ${AZURE_DOCS_RELEASE}`]
        : [
            `@azureDocs ${AZURE_DOCS_PIPELINE}`,
            `@azureDocs ${AZURE_DOCS_RELEASE}`,
          ];

  const grouped = groupByCategory(vars);
  const groupNames = [...grouped.keys()].sort();

  const lines: string[] = [];
  lines.push('/* eslint-disable */');
  lines.push('// Auto-generated by `pnpm sync-vars`. Do not edit by hand.');
  lines.push('');
  lines.push(renderTsdoc([opts.headerDoc]).trimEnd());
  lines.push(`export const ${opts.exportName} = {`);

  for (const groupName of groupNames) {
    const entries = grouped.get(groupName)!;
    if (groupName === entries[0]?.name) {
      // Single-segment variable like `TF_BUILD` — emit as a flat key.
      const v = entries[0];
      const docParas = [v.description, ...docsTags];
      lines.push(renderTsdoc(docParas, '  ').trimEnd());
      lines.push(`  ${JSON.stringify(v.name)}: ${JSON.stringify(`$(${v.name})`)} as const,`);
      continue;
    }

    lines.push(`  ${JSON.stringify(groupName)}: {`);
    for (const v of entries) {
      const tail = v.name.slice(groupName.length + 1);
      const docParas = [v.description, ...docsTags];
      lines.push(renderTsdoc(docParas, '    ').trimEnd());
      lines.push(
        `    ${JSON.stringify(tail)}: ${JSON.stringify(`$(${v.name})`)} as const,`,
      );
    }
    lines.push('  },');
  }
  lines.push('} as const;');
  lines.push('');
  return lines.join('\n');
}
