/**
 * Fetch Microsoft's predefined-variables markdown, parse, categorize, and
 * emit `packages/utils/src/predef/{pipeline,release,shared}.ts`.
 *
 * Run via `pnpm sync-vars` at the repo root (or the package).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseVariablesPage } from './parse-markdown.js';
import { categorize } from './categorize.js';
import { emitVarsFile } from './emit-vars.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../src/predef');

const SOURCES = {
  pipeline:
    'https://raw.githubusercontent.com/MicrosoftDocs/azure-devops-docs/main/docs/pipelines/build/variables.md',
  release:
    'https://raw.githubusercontent.com/MicrosoftDocs/azure-devops-docs/main/docs/pipelines/release/variables.md',
} as const;

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

const RAW_BASE = 'https://raw.githubusercontent.com/MicrosoftDocs/azure-devops-docs/main/';

/**
 * MicrosoftDocs splits the bulk of variables into INCLUDE files like
 * `[!INCLUDE [include](includes/variables-hosted.md)]`. Inline-expand them
 * recursively (single-pass — these files don't include each other).
 */
async function inlineIncludes(md: string, pageUrl: string): Promise<string> {
  const re = /\[!INCLUDE\s+\[[^\]]*\]\(([^)]+)\)\]/g;
  const matches = [...md.matchAll(re)];
  if (matches.length === 0) return md;

  // Resolve relative paths from the page URL's directory.
  const pageDir = pageUrl.replace(/\/[^/]+$/, '/');
  const docsRel = pageDir.startsWith(RAW_BASE) ? pageDir.slice(RAW_BASE.length) : '';

  let out = md;
  for (const m of matches) {
    const rel = m[1]!;
    const includeUrl = rel.startsWith('/')
      ? `${RAW_BASE}${rel.replace(/^\//, '')}`
      : `${RAW_BASE}${docsRel}${rel}`;
    try {
      const body = await fetchText(includeUrl);
      out = out.replace(m[0], body);
    } catch (err) {
      console.warn(`! skipping include ${rel}: ${(err as Error).message}`);
    }
  }
  return out;
}

async function main(): Promise<void> {
  console.log(`Fetching ${SOURCES.pipeline} ...`);
  const pipelineRaw = await fetchText(SOURCES.pipeline);
  const pipelineMd = await inlineIncludes(pipelineRaw, SOURCES.pipeline);
  console.log(`Fetching ${SOURCES.release} ...`);
  const releaseRaw = await fetchText(SOURCES.release);
  const releaseMd = await inlineIncludes(releaseRaw, SOURCES.release);

  const pipelineVars = parseVariablesPage(pipelineMd, 'pipeline');
  const releaseVars = parseVariablesPage(releaseMd, 'release');
  console.log(
    `Parsed ${pipelineVars.length} build vars + ${releaseVars.length} release vars from upstream.`,
  );

  const cat = categorize(pipelineVars, releaseVars);
  console.log(
    `Categorized: Pipeline=${cat.pipeline.length}, Release=${cat.release.length}, Shared=${cat.shared.length}, duplicated=${cat.duplicates}.`,
  );

  mkdirSync(outDir, { recursive: true });

  writeFileSync(
    resolve(outDir, 'pipeline.ts'),
    emitVarsFile(cat.pipeline, {
      exportName: 'Pipeline',
      headerDoc:
        'Predefined variables available inside YAML pipeline / build runs. ' +
        'Includes `Build.*`, `Pipeline.*`, and the build-context interpretation of `System.*` and `Agent.*`. ' +
        'Auto-generated by `pnpm sync-vars` from MicrosoftDocs/azure-devops-docs.',
      docsUrl: 'pipeline',
    }),
  );

  writeFileSync(
    resolve(outDir, 'release.ts'),
    emitVarsFile(cat.release, {
      exportName: 'Release',
      headerDoc:
        'Predefined variables available inside Classic Release runs. ' +
        'Includes `Release.*` and the release-context interpretation of `System.*` and `Agent.*`. ' +
        'Auto-generated by `pnpm sync-vars`.',
      docsUrl: 'release',
    }),
  );

  writeFileSync(
    resolve(outDir, 'shared.ts'),
    emitVarsFile(cat.shared, {
      exportName: 'Shared',
      headerDoc:
        'Predefined variables whose meaning is identical in both pipeline and release contexts. ' +
        'Auto-generated; manual hints live in `categorization-overrides.ts`.',
      docsUrl: 'both',
    }),
  );

  console.log(`Wrote pipeline.ts, release.ts, shared.ts to ${outDir}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
