/* eslint-disable */
// Auto-generated by `pnpm sync-vars`. Do not edit by hand.

/**
 * Predefined variables available inside YAML pipeline / build runs. Includes `Build.*`,
 * `Pipeline.*`, and the build-context interpretation of `System.*` and `Agent.*`.
 * Auto-generated by `pnpm sync-vars` from MicrosoftDocs/azure-devops-docs.
 */
export const Pipeline = {
  "Agent": {
    /**
     * The local path on the agent where all folders for a given build pipeline are created. This
     * variable has the same value as `Pipeline.Workspace`. For example: `/home/vsts/work/1`. For
     * more information about the agent directory structure, see [Agent directory
     * structure](../../agents/agents.md#agent-directory-structure).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "BuildDirectory": "$(Agent.BuildDirectory)" as const,
    /**
     * A mapping from container resource names in YAML to their Docker IDs at runtime.
     *
     * Example follows table.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "ContainerMapping": "$(Agent.ContainerMapping)" as const,
    /**
     * The directory the agent is installed into. This variable contains the agent software. For
     * example: `c:\agent`. For more information about the agent directory structure, see [Agent
     * directory structure](../../agents/agents.md#agent-directory-structure).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "HomeDirectory": "$(Agent.HomeDirectory)" as const,
    /**
     * The ID of the agent.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Id": "$(Agent.Id)" as const,
    /**
     * The name of the running job. This name is usually `Job`; or `__default`, but in multi-config
     * scenarios, it's the configuration.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "JobName": "$(Agent.JobName)" as const,
    /**
     * The status of the build.
     * <ul> <li>`Canceled` <li>`Failed` <li>`Succeeded` <li>`SucceededWithIssues` (partially
     * successful) <li> `Skipped` (last job) </ul>The environment variable should be referenced as
     * `AGENT_JOBSTATUS`. The older `agent.jobstatus` is available for backwards compatibility.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "JobStatus": "$(Agent.JobStatus)" as const,
    /**
     * The name of the agent that is registered with the pool.
     *
     * If you're using a self-hosted agent, then this value is the name you specify. See
     * [agents](../../agents/agents.md).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Name": "$(Agent.Name)" as const,
    /**
     * A temporary folder that is cleaned after each pipeline job. This directory is used by tasks
     * such as [.NET Core CLI task](/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2) to
     * hold temporary items like test results before they're published.
     *
     * For example: `/home/vsts/work/_temp` for Ubuntu.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TempDirectory": "$(Agent.TempDirectory)" as const,
    /**
     * The directory used by tasks such as [Node Tool
     * Installer](/azure/devops/pipelines/tasks/reference/node-tool-v0) and [Use Python
     * Version](/azure/devops/pipelines/tasks/reference/use-python-version-v0) to switch between
     * multiple versions of a tool.
     *
     * These tasks add tools from this directory to `PATH` so that subsequent build steps can use
     * them.
     *
     * Learn about [managing this directory on a self-hosted
     * agent](https://go.microsoft.com/fwlink/?linkid=2008884).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "ToolsDirectory": "$(Agent.ToolsDirectory)" as const,
    /**
     * The working directory for this agent.
     *
     * For example: `c:\agent_work`.
     *
     * Note: This directory isn't guaranteed to be writable by pipeline tasks (for example, when
     * mapped into a container). For more information about the agent directory structure, see
     * [Agent directory structure](../../agents/agents.md#agent-directory-structure).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "WorkFolder": "$(Agent.WorkFolder)" as const,
  },
  "Build": {
    /**
     * The local path on the agent where any artifacts are copied to before being pushed to their
     * destination. For example: `c:\agent_work\1\a`.
     *
     * A typical way to use this folder is to publish your build artifacts with the [Copy
     * files](/azure/devops/pipelines/tasks/reference/copy-files-v2) and [Publish build
     * artifacts](/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1) tasks.
     *
     * Note: Build.ArtifactStagingDirectory and Build.StagingDirectory are interchangeable. This
     * directory is purged before each new build, so you don't have to clean it up yourself.
     *
     * See [Artifacts in Azure Pipelines](../../artifacts/artifacts-overview.md). For more
     * information about the agent directory structure, see [Agent directory
     * structure](../../agents/agents.md#agent-directory-structure).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "ArtifactStagingDirectory": "$(Build.ArtifactStagingDirectory)" as const,
    /**
     * The local path on the agent you can use as an output folder for compiled binaries.
     *
     * On self-hosted agents, new build pipelines aren't set up to clean this directory by default.
     * You can define your build to clean it up on the [Repository tab](../../repos/index.md).
     *
     * For example: `c:\agent_work\1\b`. For more information about the agent directory structure,
     * see [Agent directory structure](../../agents/agents.md#agent-directory-structure).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "BinariesDirectory": "$(Build.BinariesDirectory)" as const,
    /**
     * The ID of the record for the completed build.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "BuildId": "$(Build.BuildId)" as const,
    /**
     * The name of the completed build, also known as the run number. You can specify [what is
     * included](../../process/run-number.md) in this value.
     *
     * A typical use of this variable is to make it part of the label format, which you specify on
     * the [repository tab](../../repos/index.md).
     *
     * Note: This value can contain whitespace or other invalid label characters. In these cases,
     * the [label format](../../../repos/tfvc/labels-command.md) fails.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "BuildNumber": "$(Build.BuildNumber)" as const,
    /**
     * The URI for the build. For example: `vstfs:///Build/Build/1430`.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "BuildUri": "$(Build.BuildUri)" as const,
    /**
     * The ID of the container for your artifact. When you upload an artifact in your pipeline,
     * it's added to a container that is specific for that particular artifact.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "ContainerId": "$(Build.ContainerId)" as const,
    /**
     * The `displayName` of the cron schedule that triggered the pipeline run. This variable is
     * only set if a YAML scheduled trigger triggers the pipeline run. For more information, see
     * [schedules.cron definition - Build.CronSchedule.DisplayName
     * variable](/azure/devops/pipelines/yaml-schema/schedules-cron#buildcronscheduledisplayname-variable).
     * This variable is available in Azure DevOps Server 2022.1 and higher.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "CronSchedule.DisplayName": "$(Build.CronSchedule.DisplayName)" as const,
    /**
     * The name of the build pipeline.
     *
     * Note: This value can contain whitespace or other invalid label characters. In these cases,
     * the [label format](../../../repos/tfvc/labels-command.md) fails.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "DefinitionName": "$(Build.DefinitionName)" as const,
    /**
     * The version of the build pipeline.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "DefinitionVersion": "$(Build.DefinitionVersion)" as const,
    /**
     * See [How are the identity variables set?](#identity_values).
     *
     * Note: This value can contain whitespace or other invalid label characters. In these cases,
     * the [label format](../../../repos/tfvc/labels-command.md) fails.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "QueuedBy": "$(Build.QueuedBy)" as const,
    /**
     * See [How are the identity variables set?](#identity_values).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "QueuedById": "$(Build.QueuedById)" as const,
    /**
     * The event that caused the build to run.
     * <ul><li>`Manual`: A user manually queued the build.</li><li>`IndividualCI`: **Continuous
     * integration (CI)** triggered by a Git push or a Team Foundation Version Control (TFVC)
     * check-in.</li><li>`BatchedCI`: **Continuous integration (CI)** triggered by a Git push or a
     * TFVC check-in, and the **Batch changes** was selected.</li><li>`Schedule`: **Scheduled**
     * trigger.</li><li>`ValidateShelveset`: A user manually queued the build of a specific TFVC
     * shelveset.</li><li>`CheckInShelveset`: **Gated check-in** trigger.</li><li>`PullRequest`: A
     * Git branch policy that requires a build triggers the build.</i><li>`BuildCompletion`:
     * [Another build triggers](../../process/pipeline-triggers.md) the
     * build.</li><li>`ResourceTrigger`: [A resource trigger](../../process/resources.md) or
     * [another build triggers](../../process/pipeline-triggers.md) the build.</li></ul>See [Build
     * pipeline triggers](../triggers.md), [Improve code quality with branch
     * policies](../../../repos/git/branch-policies.md).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Reason": "$(Build.Reason)" as const,
    /**
     * The value you selected for **Clean** in the [source repository
     * settings](../../repos/index.md).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.Clean": "$(Build.Repository.Clean)" as const,
    /**
     * The value you selected for **Checkout submodules** on the [repository
     * tab](../../repos/index.md). With multiple repos checked out, this value tracks the
     * triggering repository's setting.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.Git.SubmoduleCheckout": "$(Build.Repository.Git.SubmoduleCheckout)" as const,
    /**
     * The unique identifier of the [repository](../../repos/index.md).
     *
     * This value doesn't change, even if the name of the repository does.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.ID": "$(Build.Repository.ID)" as const,
    /**
     * The local path on the agent where your source code files are downloaded. For example:
     * `c:\agent_work\1\s`.
     *
     * On self-hosted agents, new build pipelines update only the changed files by default. You can
     * modify how files are downloaded on the [Repository tab](../../repos/index.md).
     *
     * Important note: If you check out only one Git repository, this path is the exact path to the
     * code.
     *
     * If you check out multiple repositories, the behavior is as follows (and might differ from
     * the value of the Build.SourcesDirectory variable):
     * <ul><li>If the checkout step for the self (primary) repository has no custom checkout path
     * defined, or the checkout path is the multi-checkout default path
     * `$(Pipeline.Workspace)/s/&<RepoName>` for the self repository, the value of this variable
     * reverts to its default value, which is `$(Pipeline.Workspace)/s`.</li><li>If the checkout
     * step for the self (primary) repository had a custom checkout path defined that is not its
     * multi-checkout default path, this variable contains the exact path to the self
     * repository.</li></ul>This variable is agent-scoped, and can be used as an environment
     * variable in a script and as a parameter in a build task. It can't be used as part of the
     * build number or as a version control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.LocalPath": "$(Build.Repository.LocalPath)" as const,
    /**
     * The name of the triggering [repository](../../repos/index.md).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.Name": "$(Build.Repository.Name)" as const,
    /**
     * The type of the triggering [repository](../../repos/index.md).
     * <ul><li>`TfsGit`: [TFS Git repository](../../../repos/git/index.yml)<li>`TfsVersionControl`:
     * [Team Foundation Version Control](../../../repos/tfvc/what-is-tfvc.md)<li>`Git`: Git
     * repository hosted on an external server<li>`GitHub`<li>`Svn`: Subversion</ul>This variable
     * is agent-scoped, and can be used as an environment variable in a script and as a parameter
     * in a build task. It can't be used as part of the build number or as a version control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.Provider": "$(Build.Repository.Provider)" as const,
    /**
     * Defined if your [repository](../../repos/index.md) is Team Foundation Version Control. The
     * name of the [TFVC workspace](../../../repos/tfvc/create-work-workspaces.md) used by the
     * build agent.
     *
     * For example, if the Agent.BuildDirectory is `c:\agent_work\12` and the Agent.Id is `8`, the
     * workspace name could be: `ws_12_8`
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.Tfvc.Workspace": "$(Build.Repository.Tfvc.Workspace)" as const,
    /**
     * The URL for the triggering repository. For example:
     * <ul><li>Git:
     * [https://fabrikamfiber@dev.azure.com/fabrikamfiber/_git/Scripts](https://fabrikamfiber@dev.azure.com/fabrikamfiber/_git/Scripts)<li>TFVC:
     * [https://dev.azure.com/fabrikamfiber/](https://dev.azure.com/fabrikamfiber/)</ul>This
     * variable can't be used as part of the build number or as a version control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Repository.Uri": "$(Build.Repository.Uri)" as const,
    /**
     * See "[How are the identity variables set?](#identity_values)".
     *
     * Note: This value can contain whitespace or other invalid label characters. In these cases,
     * the [label format](../../../repos/tfvc/labels-command.md) fails.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "RequestedFor": "$(Build.RequestedFor)" as const,
    /**
     * See "[How are the identity variables set?](#identity_values)".
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "RequestedForEmail": "$(Build.RequestedForEmail)" as const,
    /**
     * See "[How are the identity variables set?](#identity_values)".
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "RequestedForId": "$(Build.RequestedForId)" as const,
    /**
     * The branch of the triggering repo the build was queued for. Some examples:
     * <ul><li>Git repo branch: `refs/heads/main`</li><li>Git repo pull request:
     * `refs/pull/1/merge`</li><li>TFVC repo branch: `$/teamproject/main`</li><li>TFVC repo gated
     * check-in: `Gated_2016-06-06_05.20.51.4369;username@live.com`</li><li>TFVC repo shelveset
     * build: `myshelveset;username@live.com`</li><li>When a tag triggers your pipeline:
     * `refs/tags/your-tag-name`</li></ul>When you use this variable in your build number format,
     * the forward slash characters (`/`) are replaced with underscore characters (`_`).
     *
     * Note: In TFVC, if you're running a gated check-in build or manually building a shelveset,
     * you can't use this variable in your build number format.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "SourceBranch": "$(Build.SourceBranch)" as const,
    /**
     * The name of the branch in the triggering repo the build was queued for.
     * <ul><li>Git repo branch, pull request, or tag: The last path segment in the ref. For
     * example, in `refs/heads/main`, this value is `main`. In `refs/heads/feature/tools`, this
     * value is `tools`. In `refs/tags/your-tag-name`, this value is `your-tag-name`.</li><li>TFVC
     * repo branch: The last path segment in the root server path for the workspace. For example,
     * in `$/teamproject/main`, this value is `main`.</li><li>TFVC repo gated check-in or shelveset
     * build is the name of the shelveset. For example,
     * `Gated_2016-06-06_05.20.51.4369;username@live.com` or
     * `myshelveset;username@live.com`.</li></ul>Note: In TFVC, if you're running a gated check-in
     * build or manually building a shelveset, you can't use this variable in your build number
     * format.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "SourceBranchName": "$(Build.SourceBranchName)" as const,
    /**
     * The local path on the agent where your source code files are downloaded. For example:
     * `c:\agent_work\1\s`.
     *
     * On self-hosted agents, new build pipelines update only the changed files. For more
     * information about the agent directory structure, see [Agent directory
     * structure](../../agents/agents.md#agent-directory-structure).
     *
     * Important note: If you check out only one Git repository, this path is the exact path to the
     * code. If you check out multiple repositories, it reverts to its default value, which is
     * `$(Pipeline.Workspace)/s`, even if the self (primary) repository is checked out to a custom
     * path different from its multi-checkout default path `$(Pipeline.Workspace)/s/<RepoName>` (in
     * this respect, the variable differs from the behavior of the Build.Repository.LocalPath
     * variable).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "SourcesDirectory": "$(Build.SourcesDirectory)" as const,
    /**
     * Defined if your [repository](../../repos/index.md) is Team Foundation Version Control.
     *
     * If you're running a [gated build](../../repos/tfvc.md#gated) or a [shelveset
     * build](../../create-first-pipeline.md#queueabuild), this variable is set to the name of the
     * [shelveset](../../../repos/tfvc/suspend-your-work-manage-your-shelvesets.md) you're
     * building.
     *
     * Note: This variable yields a value that is invalid for build use in a build number format.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "SourceTfvcShelveset": "$(Build.SourceTfvcShelveset)" as const,
    /**
     * The latest version control change of the triggering repo that is included in this build.
     * <ul><li>Git: The [commit](../../../repos/git/commits.md) ID.</li><li>TFVC: the
     * [changeset](../../../repos/tfvc/find-view-changesets.md).</li></ul>This variable is
     * agent-scoped, and can be used as an environment variable in a script and as a parameter in a
     * build task. It can't be used as part of the build number or as a version control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "SourceVersion": "$(Build.SourceVersion)" as const,
    /**
     * The comment of the commit or changeset for the triggering repo. We truncate the message to
     * the first line or 200 characters, whichever is shorter.
     *
     * The `Build.SourceVersionMessage` corresponds to the message on `Build.SourceVersion` commit.
     * The `Build.SourceVersion` commit for a PR build is the merge commit (not the commit on the
     * source branch).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * Also, this variable is only available on the step level and isn't available in the job or
     * stage levels. That is, the message isn't extracted until the job starts and the code is
     * checked out.
     *
     * Note: The **Build.SourceVersionMessage** variable doesn't work with classic build pipelines
     * in Bitbucket repositories when **Batch changes while a build is in progress** is enabled.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "SourceVersionMessage": "$(Build.SourceVersionMessage)" as const,
    /**
     * The person who triggered the stage when the stage runs manually, or
     * `Microsoft.VisualStudio.Services.TFS` otherwise.
     *
     * Note: This value can contain whitespace or other invalid label characters.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StageRequestedBy": "$(Build.StageRequestedBy)" as const,
    /**
     * The GUID of identity of the person who triggered the stage when the stage runs manually, or
     * `00000002-0000-8888-8000-000000000000` otherwise.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StageRequestedForId": "$(Build.StageRequestedForId)" as const,
    /**
     * The local path on the agent where any artifacts are copied to before being pushed to their
     * destination. For example: `c:\agent_work\1\a`. For more information about the agent
     * directory structure, see [Agent directory
     * structure](../../agents/agents.md#agent-directory-structure).
     *
     * A typical way to use this folder is to publish your build artifacts with the [Copy
     * files](/azure/devops/pipelines/tasks/reference/copy-files-v2) and [Publish build
     * artifacts](/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1) tasks.
     *
     * Note: Build.ArtifactStagingDirectory and Build.StagingDirectory are interchangeable. This
     * directory is purged before each new build, so you don't have to clean it up yourself.
     *
     * See [Artifacts in Azure Pipelines](../../artifacts/artifacts-overview.md).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StagingDirectory": "$(Build.StagingDirectory)" as const,
    /**
     * If [another build triggers](../../process/pipeline-triggers.md) the build, then this
     * variable is set to the BuildID of the triggering build. In Classic pipelines, a build
     * completion trigger triggers this variable.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * If you're triggering a YAML pipeline using `resources`, you should use the [resources
     * variables](/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline#the-pipeline-resource-metadata-as-predefined-variables)
     * instead.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TriggeredBy.BuildId": "$(Build.TriggeredBy.BuildId)" as const,
    /**
     * If [another build triggers](../../process/pipeline-triggers.md) the build, then this
     * variable is set to the number of the triggering build. In Classic pipelines, a build
     * completion trigger triggers this variable.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * If you're triggering a YAML pipeline using `resources`, you should use the [resources
     * variables](/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline#the-pipeline-resource-metadata-as-predefined-variables)
     * instead.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TriggeredBy.BuildNumber": "$(Build.TriggeredBy.BuildNumber)" as const,
    /**
     * If [another build triggers](../../process/pipeline-triggers.md) the build, then this
     * variable is set to the DefinitionID of the triggering build. In Classic pipelines, a build
     * completion trigger triggers this variable.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * If you're triggering a YAML pipeline using `resources`, you should use the [resources
     * variables](/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline#the-pipeline-resource-metadata-as-predefined-variables)
     * instead.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TriggeredBy.DefinitionId": "$(Build.TriggeredBy.DefinitionId)" as const,
    /**
     * If [another build triggers](../../process/pipeline-triggers.md) the build, then this
     * variable is set to the name of the triggering build pipeline. In Classic pipelines, a build
     * completion trigger triggers this variable.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * If you're triggering a YAML pipeline using `resources`, you should use the [resources
     * variables](/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline#the-pipeline-resource-metadata-as-predefined-variables)
     * instead.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TriggeredBy.DefinitionName": "$(Build.TriggeredBy.DefinitionName)" as const,
    /**
     * If [another build triggers](../../process/pipeline-triggers.md) the build, then this
     * variable is set to ID of the project that contains the triggering build. In Classic
     * pipelines, a build completion trigger triggers this variable.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * If you're triggering a YAML pipeline using `resources`, you should use the [resources
     * variables](/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline#the-pipeline-resource-metadata-as-predefined-variables)
     * instead.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TriggeredBy.ProjectID": "$(Build.TriggeredBy.ProjectID)" as const,
  },
  "Checks": {
    /**
     * Set to 1 the first time this stage is attempted, and increments every time the stage is
     * retried.
     *
     * This variable can only be used within an [approval or check](../../process/approvals.md) for
     * an environment. For example, you could use `$(Checks.StageAttempt)` within an [Invoke REST
     * API check](../../process/approvals.md#invoke-rest-api).
     *
     * :::image type="content" source="../media/checks-stageattempt-var.png" alt-text="Add the
     * stage attempt as a parameter.":::
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StageAttempt": "$(Checks.StageAttempt)" as const,
  },
  "Common": {
    /**
     * The local path on the agent where the test results are created. For example:
     * `c:\agent_work\1\TestResults`. For more information about the agent directory structure, see
     * [Agent directory structure](../../agents/agents.md#agent-directory-structure).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TestResultsDirectory": "$(Common.TestResultsDirectory)" as const,
  },
  "Environment": {
    /**
     * ID of the environment targeted in the deployment job. For example, `10`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Id": "$(Environment.Id)" as const,
    /**
     * Name of the environment targeted in the deployment job to run the deployment steps and
     * record the deployment history. For example, `smarthotel-dev`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Name": "$(Environment.Name)" as const,
    /**
     * ID of the specific resource within the environment targeted in the deployment job to run the
     * deployment steps. For example, `4`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "ResourceId": "$(Environment.ResourceId)" as const,
    /**
     * Name of the specific resource within the environment targeted in the deployment job to run
     * the deployment steps and record the deployment history. For example, `bookings` which is a
     * Kubernetes namespace that is added as a resource to the environment `smarthotel-dev`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "ResourceName": "$(Environment.ResourceName)" as const,
  },
  "Pipeline": {
    /**
     * Workspace directory for a particular pipeline. This variable has the same value as
     * `Agent.BuildDirectory`. For example, `/home/vsts/work/1`. For more information about the
     * agent directory structure, see [Agent directory
     * structure](../../agents/agents.md#agent-directory-structure).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Workspace": "$(Pipeline.Workspace)" as const,
  },
  "Strategy": {
    /**
     * The current cycle name in a deployment. Options are `PreIteration`, `Iteration`, or
     * `PostIteration`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "CycleName": "$(Strategy.CycleName)" as const,
    /**
     * The name of the deployment strategy: `canary`, `runOnce`, or `rolling`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "Name": "$(Strategy.Name)" as const,
  },
  "System": {
    /**
     * The GUID of the Azure DevOps organization or collection.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "CollectionId": "$(System.CollectionId)" as const,
    /**
     * The URI of the Azure DevOps organization or collection. For example:
     * `https://dev.azure.com/fabrikamfiber/`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "CollectionUri": "$(System.CollectionUri)" as const,
    /**
     * [!INCLUDE [include](../includes/variables-build-sources-directory.md)]
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "DefaultWorkingDirectory": "$(System.DefaultWorkingDirectory)" as const,
    /**
     * The ID of the build pipeline.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "DefinitionId": "$(System.DefinitionId)" as const,
    /**
     * Set to `build` if the pipeline is a build. For a release, the values are `deployment` for a
     * Deployment group job, `gates` during evaluation of gates, and `release` for other (Agent and
     * Agentless) jobs.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "HostType": "$(System.HostType)" as const,
    /**
     * Set to 1 the first time this job is attempted, and increments every time the job is retried.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "JobAttempt": "$(System.JobAttempt)" as const,
    /**
     * The human-readable name given to a job.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "JobDisplayName": "$(System.JobDisplayName)" as const,
    /**
     * A unique identifier for a single attempt of a single job. The value is unique to the current
     * pipeline.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "JobId": "$(System.JobId)" as const,
    /**
     * The name of the job, typically used for expressing dependencies and accessing output
     * variables.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "JobName": "$(System.JobName)" as const,
    /**
     * Generate an `idToken` for authentication with Entra ID using OpenID Connect (OIDC). [Learn
     * more](/azure/devops/release-notes/2024/sprint-240-update#pipelines-and-tasks-populate-variables-to-customize-workload-identity-federation-authentication).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "OidcRequestUri": "$(System.OidcRequestUri)" as const,
    /**
     * Set to 1 the first time this phase is attempted, and increments every time the job is
     * retried.
     *
     * Note: "Phase" is a mostly redundant concept, which represents the design-time for a job
     * (whereas job was the runtime version of a phase). The concept of *phase* is mostly removed
     * from Azure Pipelines. Matrix and multi-config jobs are the only place where a phase is still
     * distinct from a job. One phase can instantiate multiple jobs, which differ only in their
     * inputs.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PhaseAttempt": "$(System.PhaseAttempt)" as const,
    /**
     * The human-readable name given to a phase.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PhaseDisplayName": "$(System.PhaseDisplayName)" as const,
    /**
     * A string-based identifier for a job, typically used for expressing dependencies and
     * accessing output variables.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PhaseName": "$(System.PhaseName)" as const,
    /**
     * A string-based identifier for a single pipeline run.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PlanId": "$(System.PlanId)" as const,
    /**
     * If the pull request is from a fork of the repository, this variable is set to `True`.
     *
     * Otherwise, it's set to `False`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.IsFork": "$(System.PullRequest.IsFork)" as const,
    /**
     * The ID of the pull request that caused this build. For example: `17`. (This variable is
     * initialized only if the build ran because of a [Git PR affected by a branch
     * policy](../../../repos/git/branch-policies.md#build-validation)).
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.PullRequestId": "$(System.PullRequest.PullRequestId)" as const,
    /**
     * The number of the pull request that caused this build. This variable is populated for pull
     * requests from GitHub that have a different pull request ID and pull request number. This
     * variable is only available in a YAML pipeline if a branch policy affects the PR.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.PullRequestNumber": "$(System.PullRequest.PullRequestNumber)" as const,
    /**
     * The branch that is being reviewed in a pull request. For example:
     * `refs/heads/users/raisa/new-feature` for Azure Repos. (This variable is initialized only if
     * the build ran because of a [Git PR affected by a branch
     * policy](../../../repos/git/branch-policies.md#build-validation)). This variable is only
     * available in a YAML pipeline if a branch policy affects the PR.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.SourceBranch": "$(System.PullRequest.SourceBranch)" as const,
    /**
     * The commit that is being reviewed in a pull request. (This variable is initialized only if
     * the build ran because of a [Git PR affected by a branch
     * policy](../../../repos/git/branch-policies.md#build-validation)). This variable is only
     * available in a YAML pipeline if a branch policy affects the PR.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.SourceCommitId": "$(System.PullRequest.SourceCommitId)" as const,
    /**
     * The URL to the repo that contains the pull request. For example:
     * `https://dev.azure.com/ouraccount/_git/OurProject`.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.SourceRepositoryUri": "$(System.PullRequest.SourceRepositoryUri)" as const,
    /**
     * The branch that is the target of a pull request. For example: `refs/heads/main` when your
     * repository is in Azure Repos and `main` when your repository is in GitHub. This variable is
     * initialized only if the build ran because of a [Git PR affected by a branch
     * policy](../../../repos/git/branch-policies.md#build-validation). This variable is only
     * available in a YAML pipeline if a branch policy affects the PR.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.TargetBranch": "$(System.PullRequest.TargetBranch)" as const,
    /**
     * The name of the target branch for a pull request. This variable can be used in a pipeline to
     * conditionally execute tasks or steps based on the target branch of the pull request. For
     * example, you might want to trigger a different set of tests or code analysis tools depending
     * on the branch that the changes are being merged into.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "PullRequest.targetBranchName": "$(System.PullRequest.targetBranchName)" as const,
    /**
     * Set to 1 the first time this stage is attempted, and increments every time the stage is
     * retried.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StageAttempt": "$(System.StageAttempt)" as const,
    /**
     * The human-readable name given to a stage.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StageDisplayName": "$(System.StageDisplayName)" as const,
    /**
     * A string-based identifier for a stage, typically used for expressing dependencies and
     * accessing output variables.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "StageName": "$(System.StageName)" as const,
    /**
     * The URI of the Azure DevOps organization or collection. For example:
     * `https://dev.azure.com/fabrikamfiber/`.
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TeamFoundationCollectionUri": "$(System.TeamFoundationCollectionUri)" as const,
    /**
     * The name of the project that contains this build.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TeamProject": "$(System.TeamProject)" as const,
    /**
     * The ID of the project that this build belongs to.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TeamProjectId": "$(System.TeamProjectId)" as const,
    /**
     * A string-based identifier for the execution details and logs of a single pipeline run.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     */
    "TimelineId": "$(System.TimelineId)" as const,
  },
} as const;
