/* eslint-disable */
// Auto-generated by `pnpm sync-vars`. Do not edit by hand.

/**
 * Predefined variables available inside Classic Release runs. Includes `Release.*` and the
 * release-context interpretation of `System.*` and `Agent.*`. Auto-generated by `pnpm
 * sync-vars`.
 */
export const Release = {
  "Agent": {
    /**
     * The ID of the deployment group the agent registers with. This ID is available only in
     * deployment group jobs.
     *
     * Example: `1`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DeploymentGroupId": "$(Agent.DeploymentGroupId)" as const,
    /**
     * The folder where the agent is installed. This folder contains the code and resources for the
     * agent.
     *
     * Example: `C:\agent`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "HomeDirectory": "$(Agent.HomeDirectory)" as const,
    /**
     * The name of the job that runs, such as Release or Build.
     *
     * Example: `Release`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "JobName": "$(Agent.JobName)" as const,
    /**
     * The name of the agent as registered with the [agent pool](../agents/pools-queues.md). This
     * name is likely different from the computer name.
     *
     * Example: `fabrikam-agent`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Name": "$(Agent.Name)" as const,
    /**
     * The directory to which the deployment of a release downloads artifacts. The directory is
     * cleared before every deployment if it requires artifacts to be downloaded to the agent. It's
     * the same as `System.ArtifactsDirectory` and `System.DefaultWorkingDirectory`.
     *
     * Example: `C:\agent\_work\r1\a`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ReleaseDirectory": "$(Agent.ReleaseDirectory)" as const,
    /**
     * The working directory for this agent, where subfolders are created for every build or
     * release. It's the same as `Agent.WorkFolder` and `System.WorkFolder`.
     *
     * Example: `C:\agent\_work`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "RootDirectory": "$(Agent.RootDirectory)" as const,
    /**
     * The working directory for this agent, where subfolders are created for every build or
     * release. It's the same as `Agent.RootDirectory` and `System.WorkFolder`.
     *
     * Example: `C:\agent\_work`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "WorkFolder": "$(Agent.WorkFolder)" as const,
  },
  "Build": {
    /**
     * Release.Artifacts.{Primary artifact alias}.BuildId
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "BuildId": "$(Build.BuildId)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.BuildNumber
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "BuildNumber": "$(Build.BuildNumber)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.BuildURI
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "BuildURI": "$(Build.BuildURI)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.DefinitionId
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefinitionId": "$(Build.DefinitionId)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.DefinitionName
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefinitionName": "$(Build.DefinitionName)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.PullRequest.TargetBranch
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "PullRequest.TargetBranch": "$(Build.PullRequest.TargetBranch)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.PullRequest.TargetBranchName
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "PullRequest.TargetBranchName": "$(Build.PullRequest.TargetBranchName)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.Repository.Provider
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Repository.Provider": "$(Build.Repository.Provider)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.RequestedFor
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "RequestedFor": "$(Build.RequestedFor)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.RequestedForID
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "RequestedForID": "$(Build.RequestedForID)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.SourceBranch
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "SourceBranch": "$(Build.SourceBranch)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.SourceBranchName
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "SourceBranchName": "$(Build.SourceBranchName)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.SourceVersion
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "SourceVersion": "$(Build.SourceVersion)" as const,
    /**
     * Release.Artifacts.{Primary artifact alias}.Type
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Type": "$(Build.Type)" as const,
  },
  "Release": {
    /**
     * The number of times this release is deployed in this stage.
     *
     * Example: `1`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "AttemptNumber": "$(Release.AttemptNumber)" as const,
    /**
     * The ID of the stage in the corresponding release pipeline.
     *
     * Example: `1`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefinitionEnvironmentId": "$(Release.DefinitionEnvironmentId)" as const,
    /**
     * The ID of the release pipeline to which the current release belongs.
     *
     * Example: `1`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefinitionId": "$(Release.DefinitionId)" as const,
    /**
     * The name of the release pipeline to which the current release belongs.
     *
     * Example: `fabrikam-cd`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefinitionName": "$(Release.DefinitionName)" as const,
    /**
     * The display name of the identity that triggered (started) the deployment currently in
     * progress.
     *
     * Example: `Mateo Escobedo`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Deployment.RequestedFor": "$(Release.Deployment.RequestedFor)" as const,
    /**
     * The email address of the identity that triggered (started) the deployment currently in
     * progress.
     *
     * Example: `mateo@fabrikam.com`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Deployment.RequestedForEmail": "$(Release.Deployment.RequestedForEmail)" as const,
    /**
     * The ID of the identity that triggered (started) the deployment currently in progress.
     *
     * Example: `2f435d07-769f-4e46-849d-10d1ab9ba6ab`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Deployment.RequestedForId": "$(Release.Deployment.RequestedForId)" as const,
    /**
     * The ID of the deployment. Unique per job.
     *
     * Example: `254`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DeploymentID": "$(Release.DeploymentID)" as const,
    /**
     * The ID of the phase where deployment is running.
     *
     * Example: `127`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DeployPhaseID": "$(Release.DeployPhaseID)" as const,
    /**
     * The ID of the stage instance in a release to which the deployment is currently in progress.
     *
     * Example: `276`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "EnvironmentId": "$(Release.EnvironmentId)" as const,
    /**
     * The name of stage to which deployment is currently in progress.
     *
     * Example: `Dev`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "EnvironmentName": "$(Release.EnvironmentName)" as const,
    /**
     * The URI of the stage instance in a release to which deployment is currently in progress.
     *
     * Example: `vstfs://ReleaseManagement/Environment/276`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "EnvironmentUri": "$(Release.EnvironmentUri)" as const,
    /**
     * The alias of the primary artifact source.
     *
     * Example: `fabrikam\_web`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "PrimaryArtifactSourceAlias": "$(Release.PrimaryArtifactSourceAlias)" as const,
    /**
     * The reason for the deployment. Supported values are:
     * `ContinuousIntegration` - the release started in Continuous Deployment after a build
     * completed.
     * `Manual` - the release started manually.
     * `None` - the deployment reason isn't specified.
     * `Schedule` - the release started from a schedule.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Reason": "$(Release.Reason)" as const,
    /**
     * The text description provided at the time of the release.
     *
     * Example: `Critical security patch`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ReleaseDescription": "$(Release.ReleaseDescription)" as const,
    /**
     * The identifier of the current release record.
     *
     * Example: `118`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ReleaseId": "$(Release.ReleaseId)" as const,
    /**
     * The name of the current release.
     *
     * Example: `Release-47`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ReleaseName": "$(Release.ReleaseName)" as const,
    /**
     * The URI of the current release.
     *
     * Example: `vstfs://ReleaseManagement/Release/118`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ReleaseUri": "$(Release.ReleaseUri)" as const,
    /**
     * The URL for this release.
     *
     * Example: `https://dev.azure.com/fabrikam/f3325c6c/_release?releaseId=392&_a=release-summary`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ReleaseWebURL": "$(Release.ReleaseWebURL)" as const,
    /**
     * The display name of the identity that triggered the release.
     *
     * Example: `Mateo Escobedo`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "RequestedFor": "$(Release.RequestedFor)" as const,
    /**
     * The email address of the identity that triggered the release.
     *
     * Example: `mateo@fabrikam.com`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "RequestedForEmail": "$(Release.RequestedForEmail)" as const,
    /**
     * The ID of the identity that triggered the release.
     *
     * Example: `2f435d07-769f-4e46-849d-10d1ab9ba6ab`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "RequestedForId": "$(Release.RequestedForId)" as const,
    /**
     * Boolean value that specifies whether to skip downloading of artifacts to the agent.
     *
     * Example: `FALSE`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "SkipArtifactsDownload": "$(Release.SkipArtifactsDownload)" as const,
    /**
     * The alias of the artifact which triggered the release. This value is empty when the release
     * is scheduled or triggered manually.
     *
     * Example: `fabrikam\_app`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "TriggeringArtifact.Alias": "$(Release.TriggeringArtifact.Alias)" as const,
  },
  "System": {
    /**
     * The directory to which the pipeline downloads artifacts during deployment of a release. The
     * pipeline clears the directory before every deployment if it requires artifacts to be
     * downloaded to the agent. Same as `Agent.ReleaseDirectory` and
     * `System.DefaultWorkingDirectory`.
     *
     * Example: `C:\agent\_work\r1\a`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "ArtifactsDirectory": "$(System.ArtifactsDirectory)" as const,
    /**
     * The ID of the collection to which this build or release belongs.
     *
     * Example: `6c6f3423-1c84-4625-995a-f7f143a1e43d`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "CollectionId": "$(System.CollectionId)" as const,
    /**
     * This is the only system variable that users can _set_. Set this variable to `true` to [run
     * the release in debug mode](#run-a-release-in-debug-mode) to assist in fault-finding.
     *
     * Example: `true`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Debug": "$(System.Debug)" as const,
    /**
     * The directory to which the pipeline downloads artifacts during deployment of a release. The
     * pipeline clears the directory before every deployment if it requires artifacts to be
     * downloaded to the agent. Same as `Agent.ReleaseDirectory` and `System.ArtifactsDirectory`.
     *
     * Example: `C:\agent\_work\r1\a`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefaultWorkingDirectory": "$(System.DefaultWorkingDirectory)" as const,
    /**
     * The ID of the release pipeline to which the current release belongs.
     *
     * Example: `1`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "DefinitionId": "$(System.DefinitionId)" as const,
    /**
     * The URL of the Team Foundation collection or Azure Pipelines. Use this variable in your
     * scripts or tasks to call REST APIs on other services such as Build and Version control.
     *
     * Example: `https://dev.azure.com/fabrikam/`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "TeamFoundationCollectionUri": "$(System.TeamFoundationCollectionUri)" as const,
    /**
     * The URL of the service connection in Azure Pipelines. Use this variable in your scripts or
     * tasks to call Azure Pipelines REST APIs.
     *
     * Example: `https://fabrikam.vsrm.visualstudio.com/`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "TeamFoundationServerUri": "$(System.TeamFoundationServerUri)" as const,
    /**
     * The name of the project to which this build or release belongs.
     *
     * Example: `Fabrikam`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "TeamProject": "$(System.TeamProject)" as const,
    /**
     * The ID of the project to which this build or release belongs.
     *
     * Example: `79f5c12e-3337-4151-be41-a268d2c73344`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "TeamProjectId": "$(System.TeamProjectId)" as const,
    /**
     * The working directory for this agent, where the pipeline creates subfolders for every build
     * or release. Same as `Agent.RootDirectory` and `Agent.WorkFolder`.
     *
     * Example: `C:\agent\_work`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "WorkFolder": "$(System.WorkFolder)" as const,
  },
} as const;
