/* eslint-disable */
// Auto-generated by `pnpm sync-vars`. Do not edit by hand.

/**
 * Predefined variables whose meaning is identical in both pipeline and release contexts.
 * Auto-generated; manual hints live in `categorization-overrides.ts`.
 */
export const Shared = {
  "Agent": {
    /**
     * The name of the machine on which the agent is installed.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "MachineName": "$(Agent.MachineName)" as const,
    /**
     * The operating system of the agent host. Valid values are:
     * <ul><li>`Windows_NT`<li>`Darwin`<li>`Linux`</ul>If you're running in a container, the agent
     * host and container might be running different operating systems.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "OS": "$(Agent.OS)" as const,
    /**
     * The operating system processor architecture of the agent host. Valid values are:
     * <ul><li>`X86`<li>`X64`<li>`ARM`</ul>
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "OSArchitecture": "$(Agent.OSArchitecture)" as const,
    /**
     * The version of the agent software.
     *
     * Example: `2.109.1`
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "Version": "$(Agent.Version)" as const,
  },
  "System": {
    /**
     * [Use the OAuth token to access the REST
     * API](../../scripts/powershell.md#example-powershell-script-access-rest-api).
     *
     * [Use System.AccessToken from YAML scripts](../variables.md#systemaccesstoken).
     *
     * This variable is agent-scoped, and can be used as an environment variable in a script and as
     * a parameter in a build task. It can't be used as part of the build number or as a version
     * control tag.
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
     *
     * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
     */
    "AccessToken": "$(System.AccessToken)" as const,
  },
  /**
   * Set to `True` if a build task runs the script.
   *
   * This variable is agent-scoped, and can be used as an environment variable in a script and as
   * a parameter in a build task. It can't be used as part of the build number or as a version
   * control tag.
   *
   * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/build/variables
   *
   * @azureDocs https://learn.microsoft.com/azure/devops/pipelines/release/variables
   */
  "TF_BUILD": "$(TF_BUILD)" as const,
} as const;
