import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const cliBin = resolve(here, '../dist/bin.js');
const scratchRoot = resolve(here, '../.tmp');

let dir: string;
let gitRoot: string;

beforeAll(() => {
  dir = mkdtempSync(join(scratchRoot + '-bootstrap-'));
  // Create a minimal fake git repo so findGitRoot() succeeds
  gitRoot = dir;
  mkdirSync(join(gitRoot, '.git'));
});

afterAll(() => {
  if (dir) rmSync(dir, { recursive: true, force: true });
});

function bootstrap(extraArgs: string[] = [], cwd = gitRoot): void {
  execFileSync(
    'node',
    [cliBin, 'bootstrap', '--yes', '--out', join(gitRoot, 'pipelines'), ...extraArgs],
    { stdio: 'pipe', cwd },
  );
}

describe('azpipe bootstrap', () => {
  it('scaffolds all expected files in --yes mode', () => {
    bootstrap();

    const pipelinesDir = join(gitRoot, 'pipelines');
    expect(existsSync(join(pipelinesDir, 'package.json'))).toBe(true);
    expect(existsSync(join(pipelinesDir, 'tsconfig.json'))).toBe(true);
    expect(existsSync(join(pipelinesDir, 'README.md'))).toBe(true);
    expect(existsSync(join(pipelinesDir, 'azure-pipelines.ts'))).toBe(true);
    expect(existsSync(join(pipelinesDir, 'release.ts'))).toBe(true);
    expect(existsSync(join(pipelinesDir, 'release-sync.yml'))).toBe(true);
    expect(existsSync(join(gitRoot, 'azure-pipelines.yml'))).toBe(true);
  });

  it('package.json has the right scripts', () => {
    const pkg = JSON.parse(
      readFileSync(join(gitRoot, 'pipelines', 'package.json'), 'utf8'),
    ) as Record<string, unknown>;
    const scripts = pkg['scripts'] as Record<string, string>;
    expect(scripts['build']).toContain('azpipe build azure-pipelines.ts');
    expect(scripts['diff']).toContain('azpipe release diff release.ts');
    expect(scripts['push']).toContain('azpipe release push release.ts');
    expect(scripts['push:dry']).toContain('--dry-run');
  });

  it('tsconfig.json uses NodeNext module resolution', () => {
    const tsconfig = JSON.parse(
      readFileSync(join(gitRoot, 'pipelines', 'tsconfig.json'), 'utf8'),
    ) as Record<string, unknown>;
    const co = tsconfig['compilerOptions'] as Record<string, unknown>;
    expect(co['module']).toBe('NodeNext');
    expect(co['moduleResolution']).toBe('NodeNext');
    expect(co['strict']).toBe(true);
  });

  it('azure-pipelines.yml has the generated banner', () => {
    const yml = readFileSync(join(gitRoot, 'azure-pipelines.yml'), 'utf8');
    expect(yml).toContain('GENERATED FILE');
    expect(yml).toContain('pipelines/azure-pipelines.ts');
  });

  it('release.ts contains releasePipeline()', () => {
    const ts = readFileSync(join(gitRoot, 'pipelines', 'release.ts'), 'utf8');
    expect(ts).toContain('releasePipeline(');
  });

  it('release-sync.yml contains diff and push steps', () => {
    const yml = readFileSync(join(gitRoot, 'pipelines', 'release-sync.yml'), 'utf8');
    expect(yml).toContain('azpipe release diff');
    expect(yml).toContain('azpipe release push');
    expect(yml).toContain("ne(variables['Build.Reason'], 'PullRequest')");
  });

  it('release-sync.yml uses detected or fallback branch name', () => {
    const yml = readFileSync(join(gitRoot, 'pipelines', 'release-sync.yml'), 'utf8');
    // Should include a branch trigger (main or master)
    expect(yml).toMatch(/include:\s*\n\s*- (main|master)/);
  });

  it('release-sync.yml has the source banner (not "generated by TS")', () => {
    const yml = readFileSync(join(gitRoot, 'pipelines', 'release-sync.yml'), 'utf8');
    expect(yml).toContain('pipelines/release-sync.yml');
    expect(yml).toContain('NOT compiled from TypeScript');
  });

  it('README.md contains regenerate instructions', () => {
    const readme = readFileSync(join(gitRoot, 'pipelines', 'README.md'), 'utf8');
    expect(readme).toContain('npm run build');
    expect(readme).toContain('azure-pipelines.yml');
    expect(readme).toContain('DefaultAzureCredential');
  });

  it('converts existing azure-pipelines.yml to TypeScript', () => {
    // Create a different git root with an existing YAML
    const dir2 = mkdtempSync(join(scratchRoot + '-bootstrap-conv-'));
    try {
      mkdirSync(join(dir2, '.git'));
      writeFileSync(
        join(dir2, 'azure-pipelines.yml'),
        [
          'name: CI',
          'pool:',
          '  vmImage: ubuntu-latest',
          'jobs:',
          '  - job: build',
          '    steps:',
          '      - script: npm ci',
          '        displayName: Install',
        ].join('\n') + '\n',
      );

      execFileSync(
        'node',
        [cliBin, 'bootstrap', '--yes', '--out', join(dir2, 'pipelines')],
        { stdio: 'pipe', cwd: dir2 },
      );

      const ts = readFileSync(join(dir2, 'pipelines', 'azure-pipelines.ts'), 'utf8');
      // The converted TS should have pipeline() call
      expect(ts).toContain('pipeline(');

      // Root YAML should have the generated banner prepended
      const yml = readFileSync(join(dir2, 'azure-pipelines.yml'), 'utf8');
      expect(yml).toContain('GENERATED FILE');
    } finally {
      rmSync(dir2, { recursive: true, force: true });
    }
  });

  it('shows help with --help', () => {
    const out = execFileSync('node', [cliBin, 'bootstrap', '--help'], {
      stdio: 'pipe',
      encoding: 'utf8',
    });
    expect(out).toContain('azpipe bootstrap');
    expect(out).toContain('--yes');
    expect(out).toContain('pipelines/');
  });
});
